global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'myapp'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080'] # or container-name:8090

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']